- name: check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: true

- name: Download Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust
- name: install rust/cargo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust

- name: Install Dependencies
  become: true
  ansible.builtin.apt:
    name: 
      - cmake
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
      - python3
    state: latest

- name: Install alacritty
  shell: >
    cargo install alacritty
  args:
    creates: ~/.cargo/bin/alacritty

- name: global install alacritty
  become: true
  ansible.builtin.copy:
    src: ~/.cargo/bin/alacritty
    dest: /usr/local/bin/alacritty
    owner: root
    group: root
    mode: '0644'


- name: Install lsd
  shell: >
    cargo install lsd
  args:
    creates: ~/.cargo/bin/lsd

- name: extract Nerd Font
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/Meslo.zip
    dest: /usr/share/fonts/
    remote_src: yes
- name: Update Font Cache
  become: true
  shell: >
    fc-cache -fv

- name: Link Config
  become: false
  ansible.builtin.file:
    src: '{{playbook_dir}}/../vms/ubuntu/.config/alacritty'
    dest: ~/.config/alacritty
    owner: "{{ ansible_user_id }}"
    state: link

