k9s:
  skin: cup
  liveViewAutoRefresh: false
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  enableImageScan: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: haute-cuisine-eks-production
  currentCluster: arn:aws:eks:eu-central-1:597031446072:cluster/haute-cuisine-eks-production
  keepMissingClusters: false
  clusters:
    aks-techex-dev:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - trackmyinvest
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
    aks-techex-prod:
      namespace:
        active: trackmywork
        lockFavorites: false
        favorites:
        - trackmywork
        - argocd
        - all
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
    arn:aws:eks:eu-central-1:597031446072:cluster/haute-cuisine-eks-production:
      namespace:
        active: default
        lockFavorites: false
        favorites:
        - ingress-nginx
        - kube-system
        - all
        - default
        - shopify-apps
        - traefikee
        - microservices
        - warehouse-kaki
        - warehouse-rgb
      view:
        active: pod
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
    arn:aws:eks:eu-central-1:851715686820:cluster/haute-cuisine-eks-testing:
      namespace:
        active: default
        lockFavorites: false
        favorites:
        - finance-odoo
        - shopify-apps
        - microservices
        - traefikee
        - flux-system
        - all
        - default
        - aws-cloudwatch-logs
        - warehouse
      view:
        active: ctx
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
    haute-cuisine-eks-staging:
      namespace:
        active: default
        lockFavorites: false
        favorites:
        - default
        - shopify-apps
        - flux-system
        - external-secrets
        - keda
        - kube-system
        - traefikee
        - datadog
        - all
      view:
        active: pods
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
    k3s:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - pihole
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/01/3y5lb3fs17d6g4jkgmt9fm8c0000gn/T/k9s-screens-marvinkurock
  disablePodCounting: false
