k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: haute-cuisine-eks-production
  currentCluster: arn:aws:eks:eu-central-1:597031446072:cluster/haute-cuisine-eks-production
  clusters:
    aks-techex-dev:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - trackmyinvest
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    aks-techex-prod:
      namespace:
        active: trackmywork
        lockFavorites: false
        favorites:
        - trackmywork
        - argocd
        - all
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    arn:aws:eks:eu-central-1:597031446072:cluster/haute-cuisine-eks-production:
      namespace:
        active: microservices
        lockFavorites: false
        favorites:
        - default
        - shopify-apps
        - traefikee
        - microservices
        - warehouse-kaki
        - warehouse-rgb
        - flux-system
        - keda
        - commercetools-extensions
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    arn:aws:eks:eu-central-1:851715686820:cluster/haute-cuisine-eks-testing:
      namespace:
        active: default
        lockFavorites: false
        favorites:
        - shopify-apps
        - chatbot-core
        - microservices
        - traefikee
        - flux-system
        - all
        - default
        - aws-cloudwatch-logs
        - warehouse
      view:
        active: node
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    haute-cuisine-eks-staging:
      namespace:
        active: shopify-apps
        lockFavorites: false
        favorites:
        - shopify-apps
        - flux-system
        - external-secrets
        - keda
        - kube-system
        - traefikee
        - datadog
        - all
        - microservices
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    k3s:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - pihole
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/01/3y5lb3fs17d6g4jkgmt9fm8c0000gn/T/k9s-screens-marvinkurock
