#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x feh > /dev/null || feh --bg-fill ~/wallpaper.png &
pgrep -x dunst > /dev/null || dunst &
pgrep -x polybar > /dev/null || polybar -c ~/.config/polybar/config.ini example &
pgrep -x prlcc > /dev/null || prlcc &
pgrep -x prlcp > /dev/null || prlcp &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          8
bspc config top_padding          25
