---
- name: Install and Setup Alacritty
  hosts: localhost
  tasks:
    - name: check if cargo is installed
      shell: command -v cargo
      register: cargo_exists
      ignore_errors: yes
    - name: Download Installer
      when: cargo_exists is failed
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: '0755'
        force: 'yes'
      tags:
        - rust
    - name: install rust/cargo
      when: cargo_exists is failed
      shell: /tmp/sh.rustup.rs -y
      tags:
        - rust

    - name: Install Dependencies
      become: true
      ansible.builtin.apt:
        name: 
          - cmake
          - pkg-config
          - libfreetype6-dev
          - libfontconfig1-dev
          - libxcb-xfixes0-dev
          - libxkbcommon-dev
          - python3
        state: latest

    - name: Install alacritty
      shell: >
        cargo install alacritty
        creates=~/.cargo/bin/alacritty

    - name: extract Nerd Font
      become: true
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/Meslo.zip
        dest: /usr/share/fonts/
        remote_src: yes
    - name: Update Font Cache
      become: true
      shell: >
        fc-cache -fv

    - name: Link Config
      become: false
      ansible.builtin.file:
        src: '{{playbook_dir}}/../vms/ubuntu/.config/alacritty'
        dest: ~/.config/alacritty
        owner: marvin
        state: link

    - name: Install shell
      become: true
      ansible.builtin.apt:
        name:
          - zsh
          - tmux
        state: latest

    - name: check ohmyzsh
      stat:
        path: ~/.oh-my-zsh/oh-my-zsh.sh
      register: stat_ohmyzsh

    - name: Install ohmyzsh
      when: not stat_ohmyzsh.stat.exists
      shell: |
        sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

    - name: Link zshrc
      ansible.builtin.file:
        src: '{{playbook_dir}}/../vms/ubuntu/.zshrc'
        dest: ~/.zshrc
        owner: marvin
        state: link
        force: true
    - name: change shell
      become: true
      ansible.builtin.user:
        name: marvin
        shell: /bin/zsh



- name: Install Neovim
  hosts: localhost
  become: true
  tasks:
    - name: Install Dependencies
      ansible.builtin.apt:
        name: 
          - cmake
          - ninja-build 
          - gettext 
          - unzip 
          - curl
        state: latest
    - name: clone repo
      ansible.builtin.git:
        repo: https://github.com/neovim/neovim.git
        dest: /opt/neovim
        update: no
        version: release-0.9
    - name: build neovim
      community.general.make:
        chdir: /opt/neovim
        target: all
        params:
          CMAKE_BUILD_TYPE: RelWithDebInfo
    - name: install neovim
      community.general.make:
        chdir: /opt/neovim
        target: install
    - name: Link Config
      become: false
      ansible.builtin.file:
        src: '{{playbook_dir}}/../.config/nvim'
        dest: ~/.config/nvim
        owner: marvin
        state: link

- name: Install Node
  hosts: localhost
  tasks:
    - name: Install nvm
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
        creates=/home/{{ ansible_user_id }}/.nvm/.nvm.sh
    - name: Install node and set version
      shell: >
        /bin/bash -c "source ~/.nvm/nvm.sh && nvm install node && nvm alias default node"
        creates=/home/{{ ansible_user_id }}/.nvm/alias



